sources:
  - Playfair.glyphspackage
  - Playfair-Italic.glyphspackage
axisOrder:
  - opsz
  - wght
  - ital
familyName: Playfair Mono
buildStatic: false
cleanUp: true
fvarInstanceAxisDflts:
  opsz: 12
  wght: 400
stat:
  PlayfairMono[opsz,wght].ttf:
  - name: Optical size
    tag: opsz
    values:
    - name: 6pt
      value: 6
    - name: 7pt
      value: 7
    - name: 8pt
      value: 8
    - name: 12pt
      value: 12
    - name: 16pt
      value: 16
    - name: 48pt
      value: 48
    - name: 72pt
      value: 72
    - name: 96pt
      value: 96
  - name: Weight
    tag: wght
    values:
    - name: Light
      value: 300
    - name: Regular
      value: 400
      linkedValue: 700
      flags: 2
    - name: Medium
      value: 500
    - name: SemiBold
      value: 600
    - name: Bold
      value: 700
    - name: ExtraBold
      value: 800
    - name: Black
      value: 900
  - name: Italic
    tag: ital
    values:
    - name: Roman
      value: 0
      linkedValue: 1
      flags: 2
  PlayfairMono-Italic[opsz,wght].ttf:
  - name: Optical size
    tag: opsz
    values:
    - name: 6pt
      value: 6
    - name: 7pt
      value: 7
    - name: 8pt
      value: 8
    - name: 12pt
      value: 12
    - name: 16pt
      value: 16
    - name: 48pt
      value: 48
    - name: 72pt
      value: 72
    - name: 96pt
      value: 96
  - name: Weight
    tag: wght
    values:
    - name: Light
      value: 300
    - name: Regular
      value: 400
      linkedValue: 700
      flags: 2
    - name: Medium
      value: 500
    - name: SemiBold
      value: 600
    - name: Bold
      value: 700
    - name: ExtraBold
      value: 800
    - name: Black
      value: 900
  - name: Italic
    tag: ital
    values:
    - name: Italic
      value: 1
